POST http://localhost:3000/passengers HTTP/1.1
content-type: application/json

{
  "name":"Mike",
  "surname":"Odd",
  "email":"dino@gmail.com",
  "phone":"+1 (407)-733 0530"}


###

GET http://localhost:3000/passengers/61070663b1bbe03a1835e498 HTTP/1.1

###

DELETE http://localhost:3000/passengers/61070663b1bbe03a1835e498 HTTP/1.1

###

PATCH http://localhost:3000/passengers/61070663b1bbe03a1835e498 HTTP/1.1
content-type: application/json

{"name":"Mike"}

###

POST http://localhost:3000/drivers HTTP/1.1
content-type: application/json

{ 
  "name":"Kate",
  "surname":"Mingo",
  "email":"Kate2@gmail.com",
  "phone":"+1 (202)-733 0530",
  "drivinglicense":"1112223354543"}

###
GET http://localhost:3000/drivers/6109247bb24d7a2c98c95f76 HTTP/1.1

###
DELETE http://localhost:3000/drivers/6103ef7533187073e8f4eeae HTTP/1.1

###
PATCH http://localhost:3000/drivers/610d79a2d04a1f424447458c HTTP/1.1
Content-Type: application/json

{
  "surname":"Pan"
}

###

POST http://localhost:3000/drivers/611257066dfcf269f047716f/vehicles HTTP/1.1
Content-Type: application/json

{
  "type":"Car",
  "brand":"Volvo",
  "model":"X60",
  "year":"2012"
}

###

DELETE http://localhost:3000/drivers/6109247bb24d7a2c98c95f76/vehicles/610be381e311c55250b61972 HTTP/1.1


###

POST http://localhost:3000/drivers/611257066dfcf269f047716f/trips?vehicleId=611257196dfcf269f0477172 HTTP/1.1
Content-Type: application/json

{
  "tripDate":"2021-10-18T16:00:00Z",
  "from":"Istanbul",      
  "destination":"Ankara",
  "availableSeat":2,
  "price":100
}

###

PATCH http://localhost:3000/drivers/611257066dfcf269f047716f/trips/6112572d6dfcf269f0477172 HTTP/1.1
Content-Type: application/json

{
  "tripDate":"2021-10-28T16:00:00Z"
}


###

DELETE  http://localhost:3000/drivers/611257066dfcf269f047716f/trips/6112572d6dfcf269f0477179 HTTP/1.1
