POST http://localhost:3000/passengers HTTP/1.1
content-type: application/json

{
  "name":"George",
  "surname":"Odd",
  "email":"george@gmail.com",
  "phone":"123456789"}


###

GET http://localhost:3000/passengers/6103178b4d298730a83b6ff2 HTTP/1.1

###

DELETE http://localhost:3000/passengers/61031891061e7861e444ea88 HTTP/1.1

###

PATCH http://localhost:3000/passengers/6103178b4d298730a83b6ff2 HTTP/1.1
content-type: application/json

{"name":"new name4"}